### ISSUE TITLE
Create coverpage for September ballot

### ISSUE THREAD

**Issue by IoanaSingureanu** [HL7/ANF#3]
- Populate the [coverpage template](https://confluence.hl7.org/download/attachments/35719174/Ballot_CoverPage_Template_2019SEP.doc?version=1&modificationDate=1561124240406&api=v2) according to the ANF ballot announcement.

- Create a PDF of the coverpage and push it to GitHub to reuse for building the ballot package

**Comment by IoanaSingureanu** [comment]
HL7 CIMI Logical Model: Analysis Normal Form (ANF), Release 1
HL7_CIMI_LM_ANF_R1_I1_2019SEP

**Comment by IoanaSingureanu** [comment]
Edited the coverpate and created draft publication:
https://github.com/HL7/ANF/blob/master/document-storage/HL7_CIMI_LM_ANF_R1_I1_2019SEP.pdf

**Comment by resmond** [comment]
Ioana -

 I wanted you all to know that I'm not going to be available today.

I have four new hires and an additional half dozen Interns that I am
juggling.

If you guys need anything from my side, let me know via email, which I am
checking continually.

Richard
